### ISSUE TITLE
Add support for Amazon Echo

### ISSUE THREAD

**Issue by jimboca** [falk0069/hue-upnp#2]
Really appreciate this work!  It works great with my Harmony hub, do you know if anyone has tried to get this working with an Amazon Echo?  I tried, but the Echo is not recognizing it.  If you don't know, then I am go to look into getting it working.

**Comment by jimboca** [comment]
I can see the Echo (74) upnp requst, and it sends back the description.xml

```
2015-09-06 09:11:24,086 [INFO ] received M-SEARCH from ('192.168.1.74', 50000)
2015-09-06 09:11:24,087 [DEBUG]  data:
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: urn:Belkin:device:**
2015-09-06 09:11:24,088 [DEBUG] ignoring
2015-09-06 09:11:24,089 [DEBUG] ----------------------
2015-09-06 09:11:24,090 [DEBUG]
2015-09-06 09:11:24,187 [INFO ] received M-SEARCH from ('192.168.1.74', 50000)
2015-09-06 09:11:24,188 [DEBUG]  data:
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: urn:Belkin:device:**
2015-09-06 09:11:24,189 [DEBUG] ignoring
2015-09-06 09:11:24,190 [DEBUG] ----------------------
2015-09-06 09:11:24,191 [DEBUG]
2015-09-06 09:11:24,294 [INFO ] received M-SEARCH from ('192.168.1.74', 50000)
2015-09-06 09:11:24,295 [DEBUG]  data:
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: urn:schemas-upnp-org:device:basic:1
2015-09-06 09:11:24,296 [DEBUG] received urn:schemas-upnp-org:device:basic:1
2015-09-06 09:11:24,297 [INFO ] Response sent: http://192.168.1.77:80/description.xml
2015-09-06 09:11:24,298 [DEBUG] ----------------------
2015-09-06 09:11:24,299 [DEBUG]
2015-09-06 09:11:24,405 [INFO ] received M-SEARCH from ('192.168.1.74', 50000)
2015-09-06 09:11:24,406 [DEBUG]  data:
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: urn:schemas-upnp-org:device:basic:1
2015-09-06 09:11:24,407 [DEBUG] received urn:schemas-upnp-org:device:basic:1
2015-09-06 09:11:24,408 [INFO ] Response sent: http://192.168.1.77:80/description.xml
2015-09-06 09:11:24,409 [DEBUG] ----------------------
2015-09-06 09:11:24,409 [DEBUG]
2015-09-06 09:11:24,550 [INFO ] http request from 192.168.1.74
2015-09-06 09:11:24,551 [DEBUG] HTTP Request: GET /description.xml HTTP/1.1
Host: 192.168.1.77
Accept: */*
2015-09-06 09:11:24,552 [INFO ] http request from 192.168.1.74
2015-09-06 09:11:24,553 [INFO ] Sent HTTP description.xml Response
2015-09-06 09:11:24,553 [DEBUG] -------------------------------
2015-09-06 09:11:24,554 [DEBUG] HTTP Request: GET /description.xml HTTP/1.1
Host: 192.168.1.77
Accept: */*
2015-09-06 09:11:24,555 [DEBUG]
2015-09-06 09:11:24,556 [INFO ] Sent HTTP description.xml Response
2015-09-06 09:11:24,557 [DEBUG] -------------------------------
2015-09-06 09:11:24,558 [DEBUG]
2015-09-06 09:11:32,532 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:32,534 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:schemas-upnp-org:service:ContentDirectory:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:32,535 [DEBUG] ignoring
2015-09-06 09:11:32,536 [DEBUG] ----------------------
2015-09-06 09:11:32,536 [DEBUG]
2015-09-06 09:11:32,537 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:32,538 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:32,539 [DEBUG] ignoring
2015-09-06 09:11:32,540 [DEBUG] ----------------------
2015-09-06 09:11:32,541 [DEBUG]
2015-09-06 09:11:32,834 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:32,835 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:schemas-upnp-org:service:ContentDirectory:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:32,836 [DEBUG] ignoring
2015-09-06 09:11:32,837 [DEBUG] ----------------------
2015-09-06 09:11:32,838 [DEBUG]
2015-09-06 09:11:32,839 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:32,840 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:32,841 [DEBUG] ignoring
2015-09-06 09:11:32,842 [DEBUG] ----------------------
2015-09-06 09:11:32,843 [DEBUG]
2015-09-06 09:11:33,136 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:33,137 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:schemas-upnp-org:service:ContentDirectory:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:33,138 [DEBUG] ignoring
2015-09-06 09:11:33,139 [DEBUG] ----------------------
2015-09-06 09:11:33,140 [DEBUG]
2015-09-06 09:11:33,141 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:33,142 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:33,143 [DEBUG] ignoring
2015-09-06 09:11:33,144 [DEBUG] ----------------------
2015-09-06 09:11:33,144 [DEBUG]
2015-09-06 09:11:33,438 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:33,439 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:schemas-upnp-org:service:ContentDirectory:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:33,440 [DEBUG] ignoring
2015-09-06 09:11:33,441 [DEBUG] ----------------------
2015-09-06 09:11:33,442 [DEBUG]
2015-09-06 09:11:33,443 [INFO ] received M-SEARCH from ('169.254.198.241', 4996)
2015-09-06 09:11:33,444 [DEBUG]  data:
M-SEARCH * HTTP/1.1
MX: 10
ST: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
2015-09-06 09:11:33,445 [DEBUG] ignoring
2015-09-06 09:11:33,446 [DEBUG] ----------------------
2015-09-06 09:11:33,446 [DEBUG]
```

Any clue you can provide would be appreciated.  I'm doing some research.

**Comment by falk0069** [comment]
Jimboca,

I appreciate you experimenting with this.  It would nice to see the Echo work as well, but as I’ve seen 3rd party integration can be very picky if you don’t know what exactly it is looking for.  

Looking at the log you provided I see the Echo (at 192.168.1.74) is sending “urn:schemas-upnp-org:device:basic:1”.  This is good.  I then see the description.xml location is sent back—also is good.

I then see the Echo come and grab the description.xml:

2015-09-06 09:11:24,550 [INFO ] http request from 192.168.1.74
2015-09-06 09:11:24,551 [DEBUG] HTTP Request: GET /description.xml HTTP/1.1

And the hue-upnp responds back with it:

2015-09-06 09:11:24,553 [INFO ] Sent HTTP description.xml Response

The traffic then stops.  I believe the next thing you should see in the log is something like this:

2015-09-06 12:09:59,739 [INFO ] http request from 192.168.1.74
2015-09-06 12:09:59,776 [DEBUG] HTTP Request: POST /api/ HTTP/1.1
connection: close, TE
content-length: 28
user-agent: LuaSocket 2.0.2
te: trailers
content-type: application/json
host: 192.168.1.77

{"devicetype":"Amazon Echo Maybe?"}
2015-09-06 12:09:59,776 [INFO ] Sent HTTP New Dev Sync Response
2015-09-06 12:09:59,777 [DEBUG] -------------------------------

The Echo never seems to be sending this JSON POST.  There must be something in the Description.xml that the Echo doesn’t like.  I think the description.xml response is where you need to focus.  I know there are some hardcoded elements in that XML. Maybe the modelNumber/UUID needs to be different?  Or maybe we need to specify something in the services.  Perhaps it doesn’t like the <URLBase>?  I see you are using port 80 for the service, which should be the most compatible.  This will make URLBase in the description.xml be:

<URLBase>http://192.168.1.77:80/</URLBase>

Maybe the Echo is tripping over the :80 in the URL?  You could try removing the port in the code by editing these lines:

Line 79:

```
   <URLBase>http://{}/</URLBase>
```

Line 119:

""".format(IP, IP, SERIALNO, SERIALNO).replace("\n", "\r\n")

Good luck and let me know if you make any progress.

Thanks

--Andy

**Comment by jimboca** [comment]
Thank you very much for the tips.  I will try your suggestions.

**Comment by falk0069** [comment]
Jimboca,

I’ve been searching online for other ‘official’ description.xml responses that others have reported.  All the examples I’ve found seem to indicate that the official hue will send back a :PORT in the description.xml, so scrubbing that likely won’t help.

Looking at the example here:

https://www.safaribooksonline.com/library/view/abusing-the-internet/9781491902899/ch04.html

I see that they specify UTF-8 on the xml line:

<?xml version="1.0" encoding="UTF-8" ?>

I also see they completely omit the services section:

<serviceList>

Looking on this site the user posts the XML that was captured in a file:

http://tech.reboot.pro/showthread.php?tid=4624

I’m not sure if it was formatted or not from what was sent over the wire, but the <root> tag does not include the schema:

<root xmlns="urn:schemas-upnp-org:device-1-0">

It also has all newlines removed and it also omits the <serviceList> tag.

One of these minor differences might be what makes the Echo refuse to accept the description, but who knows.  It would really help of we could find a real network capture of the Hue and what actually gets sent.  I don’t own a Hue so I can’t capture one—I’ve only based the code on what I’ve found online from others.

Another thing I thought of is maybe the MacAddress/HWaddr is being used.  On your server (192.168.1.77) you can grab it via the ifconfig command:

/sbin/ifconfig -a | grep -B1 192.168.1.77

Then update it in the hueUpnp.py:

MACADDRESS = "00:17:88:17:12:2c"

Good luck—I hope you figure something out.

Thanks

--Andy

**Comment by jimboca** [comment]
Andy,

Wow, thanks for all the research! I will try out your suggestions, but
probably not until tomorrow, I'm kinda brain dead from furniture shopping
with my wife most of the day.
- Jim

**Comment by falk0069** [comment]
Jim,,

I found this other java project that support the Echo: https://github.com/armzilla/amazon-echo-ha-bridge

One thing I've found so far is in the Description.xml the <modelName> is set to:
"Philips hue bridge 2012" without the "Router" appended.  This might be a quick test for you to run.  I'm trying to identify other differences that might be at play.  I'll let you know if I find anything.

-Andy

**Comment by jimboca** [comment]
Andy,

Yes, that emulator does work, and I know others are using it with the ISY,
and another version released by http://bwssystems.com/ that looks to be a
copy of that code. Thanks for the pointer, I hope to have time next week to
play with this more when I get back from vacation.
- Jim

**Comment by falk0069** [comment]
Jim,

## I uploaded a newer version of the code.  I'm not sure if it will help, but maybe it will.  Here are the comments I added:

Updated the description.xml to contain the Modelname: Philips hue bridge 2012 (omitted the Router).  Also removed the tab indents and carriage returns (\r) because examples found on the web didn't seem to have these.

Also added in the GET /api/*/config option so it will return the JSON configuration description.  Some devices might be using this to distinguish the Hue.

Lastly, I added in the "ssdp:all" so the server responds to it as upnp:rootdevice.

## I have no idea if it will help or not but it is the best I can find based on examples scattered over the net.

Whenever you have time, can you try it out?   If it doesn't work, would you be willing to provide a tcpdump?  It would be best to do it with a working emulator you've found but the results from the hue-upnp would also be useful.

Assuming your Echo is still at 192.168.1.74, you can run this on Linux:
sudo /usr/sbin/tcpdump -i any -s 0 -w /tmp/echotrace.cap host 192.168.1.74

Or if running on Windows, use Wireshark with the same filter:
host 192.168.1.74

Let me know if you can help.

Thanks

--Andy

**Comment by jimboca** [comment]
Andy,

Thanks!  I will give this a try as soon as I can, that all sounds
promising, and if not I will run the java emulator and see what tcpdump
shows.

Thanks again for looking into this,
- Jim

**Comment by jimboca** [comment]
Andy,

You did it!!!  Success with Alexa finding the devices.  This will be awesome.

Thanks,
Jim

**Comment by jimboca** [comment]
It looks like the code is expecting the PUT request to be /api/lights/1/state, but Alexa is passing back an id after the /api so it's not recognizing it.

```
2015-09-27 15:40:07,156 [DEBUG] HTTP Request: PUT /api/RHm5yV82JuwvAhXEg5rsfzbKLI9fYi2LLccuD0Od/lights/1/state HTTP/1.1

Host: 192.168.1.77

Accept: */*

Content-type: application/x-www-form-urlencoded

Content-Length: 12



{"on": true}
```

But this is looking really good.  Wish I had more time to work on this today.

**Comment by falk0069** [comment]
Sweet--great progress.  I think this should be an easy fix now to get the rest working.  I might take a look now if my wife doesn't call me up for something. 

I'm curious--did you get it to work on port 8080? or a non port-80 port?  Did you have to editing any of the other variables?

Thanks
--Andy

**Comment by jimboca** [comment]
I tried once on a different port and it didn't work. But I didn't look into it further, although I do need it on a different port for my application.

**Comment by falk0069** [comment]
Okay, I just uploaded a new version.  I updated the GETs as well because I bet the same thing is happening to them when request the states.  I basically just updated the code to use a regular expression and allow "/api/.*lights", so it should now work either way.  Hopefully this does it.  Thanks for all the details.
--Andy

**Comment by jimboca** [comment]
Thanks I'll try it

**Comment by jimboca** [comment]
Getting even closer.

```
2015-09-28 18:48:23,275 [DEBUG] -------------------------------
2015-09-28 18:48:23,276 [DEBUG]
2015-09-28 18:48:32,702 [DEBUG] HTTP Request: PUT /api/RHm5yV82JuwvAhXEg5rsfzbKLI9fYi2LLccuD0Od/lights/1/state HTTP/1.1
Host: 192.168.1.77
Accept: */*
Content-type: application/x-www-form-urlencoded
Content-Length: 12

{"on": true}
2015-09-28 18:48:32,706 [DEBUG] Got PUT request to do something
2015-09-28 18:48:32,709 [DEBUG] PUT Request: 1 |-| on |-|  true
2015-09-28 18:48:32,723 [DEBUG] Sent HTTP Put Response:
[{"success":{"/lights/1/state/on": true}}]
```

But Alexa is not happy with the response.   I'll try to look more later tonight.

**Comment by falk0069** [comment]
It looks like it at least got into the section of code that should be calling the hue-upnp-helper.sh script.  Is it executing the the script at least?  Let me know what you find out.

**Comment by jimboca** [comment]
Yes, it is executing the script, for now I just have the script defined as '/bin/true' so it always runs.  

I tried adding the uniqueId to the success response,but Alexa still doesn't think it was successful.

```
2015-09-28 20:14:48,537 [DEBUG] -------------------------------
2015-09-28 20:14:48,538 [DEBUG]
2015-09-28 20:14:50,956 [DEBUG] HTTP Request: PUT /api/RHm5yV82JuwvAhXEg5rsfzbKLI9fYi2LLccuD0Od/lights/1/state HTTP/1.1
Host: 192.168.1.77
Accept: */*
Content-type: application/x-www-form-urlencoded
Content-Length: 12

{"on": true}
2015-09-28 20:14:50,957 [DEBUG] Got PUT request to do something
2015-09-28 20:14:50,958 [DEBUG] PUT Request: 1 |-| on |-|  true
2015-09-28 20:14:50,971 [DEBUG] Sent HTTP Put Response:
[{"success":{"/RHm5yV82JuwvAhXEg5rsfzbKLI9fYi2LLccuD0Od/lights/1/state/on": true}}]
```

I tried a few different combinations but it always says the device is not responding.   Don't have more time tonight, but will try to research what others are doing for the response.   It might even be that Alexa doesn't wait for the response, it just starts querying all lights to see what they are set to. It's a little hard to tell from the log because Alexa and my Harmony hub are talking to the server at the same time so I need to have the clarify where things are coming from, or just disconnect the harmony while I'm testing.  I probably won't have any more time this week to look at it...

**Comment by jimboca** [comment]
I finally had some time to look into this again, and I found the problem.  I added some more debug printing to see what it was doing, inside the handle method it is calling recv up to 4 times depending on what data it sees, so I print out each time it received data.

The Harmony hub sends a request like this:

```
2015-10-11 14:05:41,436 [DEBUG] 192.168.1.98 HTTP Request 1: PUT /api/lights/1/state HTTP/1.1
2015-10-11 14:05:41,445 [DEBUG] 192.168.1.98 HTTP Request 2: PUT /api/lights/1/state HTTP/1.1
connection: close, TE
content-length: 12
user-agent: LuaSocket 2.0.2
te: trailers
content-type: application/json
host: 192.168.1.77
2015-10-11 14:05:41,448 [DEBUG] 192.168.1.98 HTTP Request Full: PUT /api/lights/1/state HTTP/1.1
connection: close, TE
content-length: 12
user-agent: LuaSocket 2.0.2
te: trailers
content-type: application/json
host: 192.168.1.77

{"on":false}
```

The Echo sends this:

```
2015-10-11 14:02:05,588 [DEBUG] 192.168.1.74 HTTP Request 1: PUT /api/RHm5yV82JuwvAhXEg5rsfzbKLI9fYi2LLccuD0Od/lights/1/state HTTP/1.1
Host: 192.168.1.77
Accept: */*
Content-type: application/x-www-form-urlencoded
Content-Length: 12

{"on": true}
2015-10-11 14:02:26,814 [DEBUG] 192.168.1.74 HTTP Request Full: PUT /api/RHm5yV82JuwvAhXEg5rsfzbKLI9fYi2LLccuD0Od/lights/1/state HTTP/1.1
Host: 192.168.1.77
Accept: */*
Content-type: application/x-www-form-urlencoded
Content-Length: 12

{"on": true}
```

As shown in the log, it takes over 20 seconds to get the 'Full' response, so I guess each call to recv has to timeout.

I have added a temporary hack to ignore trying to read more data if it sees the application/x-www-form-urlencoded line, you can check my current fork if you want to see my debug lines and hack.

I'm thinking that handle method should be changed to read lines so it can get through the headers, then read the actual data if available?

**Comment by falk0069** [comment]
Jim,
I'm having trouble understanding the difference between the 1 vs. Full requests.  It sounds like this issue you found happens for the Harmony hub as well but it is quicker at sending the 'Full' request.  Am I understanding correctly?

I'm looking at the two Echo log entries you have and they look identical to me except for the "Full" vs. "1" .  Am I missing something?  I don't understand why after 20 seconds it would be any different.  I'm not sure when I'm going to have a chance to look at your code, but I will eventually.

One thing can say is I did have a bunch of problems with getting all the data in on the requests.  The original code only called recv once.  Some calls I found would come in via multiple packets for some reason.  That is why there are multiple calls to revc().    Each time I'm looking for the end of the header "\r\n\r\n".  Once I know I've collected the entire header I search for the 'content-length', so I know how much is left and I grab the rest.

The fact that you say you are blocking the read for more data confuses me.  I'm beginning to wonder if perhaps everything is pulled in during the first revc(); and the final revc() being done, just has to wait until it times out since there is nothing more that will be sent.

You definitely got me interesting, but it will be a few days before I can find time to dive in deeper.

--Andy

**Comment by falk0069** [comment]
Okay, I glance at you code and I do believe that is the problem.  The Echo is sending everything in the first packet.  So it is hanging on the final recv:
data += self.request.recv(int(searchObj.group(1)))

A quick hack might be to skip that final recv if "}" in data.  A better solution would be to compute the header size + the Content-Length" and see if that is the current size of data.  I'll mess around with that later this week or next.
--Andy

**Comment by jimboca** [comment]
Andy,

Yes, exactly, that's what I was thinking, to parse the headers and content
a little cleaner.  I've also done a bunch of cleanup to the code to make it
easier to be called as an object inside another Python program, but have
some more cleanup to do that I hope to get done this week.  I'd also like
to add proper json parsing, instead of using regexp's, but not sure if I
can get that much done this week.

It's really awesome to ask Alexa to turn on a light which uses Insteon
managed by my ISY and then see the status also reflected inside my harmony
remote!
- Jim

**Comment by falk0069** [comment]
Jim,

Adding in the header size calculation was easier than I though.  I just had to do this:
headerLength = data.find("\r\n\r\n") + 4

Then I only request additional data if we don't have enough yet:
if len(data) < headerLength + contentLength:
        data += self.request.recv(headerLength + contentLength - len(data))

I committed this update.  Hopefully you find it useful.

Let me know if you come up with a better json parser.

Thanks
--Andy

**Comment by jimboca** [comment]
Looks great, I will try to test that tonight with Alexa.

**Comment by jimboca** [comment]
Works perfectly with Harmony and Alexa. :-)

**Comment by jimboca** [comment]
Latest version includes using the json parser to read the device command, let me know what you think of all the changes.  It's all working for me with the Android Hue app, Harmony Hub, and Amazon Echo.

**Comment by falk0069** [comment]
Just letting you know that I'm planning on looking at your changes and testing it out with my system--I just haven't had time to do it yet.  Once I validate it, I'll likely merge your code with mine.
Thanks
--Andy

**Comment by jimboca** [comment]
Thanks, hopefully it all goes well and you are ok with the changes. I am out of town till Thursday, so I can make any changes you want when I get back. I appreciate you letting me know.

**Comment by falk0069** [comment]
Jim,

I just wanted to touch base with you and make sure you saw my comments on your code merge.  No huge rush.

Thanks
--Andy

**Comment by jimboca** [comment]
Yes I did see your comments, sorry I haven't had time to answer them yet.
